# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-d17152c2-cc3b-4954-8ba8-e1909f251362";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-d17152c2-cc3b-4954-8ba8-e1909f251362".device = "/dev/disk/by-uuid/d17152c2-cc3b-4954-8ba8-e1909f251362";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/CDC4-3CEA";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d7c2cbf4-97e3-4275-86be-d0715bba8399"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
