#!/bin/bash

if xrandr | grep -q "DP-4 connected"; then
  # External monitor connected
  xrandr --output eDP-1 --off --output DP-4 --auto --scale 1x1 --transform 1,0,0,0,1,0,0,0,1
  echo "Xft.dpi: 96" | xrdb -merge
else
  # External monitor not connected, use laptop screen
  xrandr --output DP-4 --off --output eDP-1 --auto --scale 1x1 --transform 1,0,0,0,1,0,0,0,1
  echo "Xft.dpi: 192" | xrdb -merge
fi
